// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderManagement.Server.AppDbContext;

#nullable disable

namespace OrderManagement.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderManagement.Server.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Order", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "New York Building 1",
                            State = "NY"
                        },
                        new
                        {
                            Id = 2,
                            Name = "California Hotel AJK",
                            State = "CA"
                        });
                });

            modelBuilder.Entity("OrderManagement.Server.Models.Subelement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.Property<int>("WindowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WindowId");

                    b.ToTable("Subelement", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Height = 1850,
                            Type = "Doors",
                            Width = 1200,
                            WindowId = 1
                        },
                        new
                        {
                            Id = 2,
                            Height = 1850,
                            Type = "Window",
                            Width = 800,
                            WindowId = 1
                        },
                        new
                        {
                            Id = 3,
                            Height = 1850,
                            Type = "Window",
                            Width = 700,
                            WindowId = 1
                        },
                        new
                        {
                            Id = 4,
                            Height = 2000,
                            Type = "Window",
                            Width = 1500,
                            WindowId = 2
                        },
                        new
                        {
                            Id = 5,
                            Height = 2200,
                            Type = "Doors",
                            Width = 1400,
                            WindowId = 3
                        },
                        new
                        {
                            Id = 6,
                            Height = 2200,
                            Type = "Window",
                            Width = 600,
                            WindowId = 3
                        },
                        new
                        {
                            Id = 7,
                            Height = 2000,
                            Type = "Window",
                            Width = 1500,
                            WindowId = 4
                        },
                        new
                        {
                            Id = 8,
                            Height = 2000,
                            Type = "Window",
                            Width = 1500,
                            WindowId = 4
                        });
                });

            modelBuilder.Entity("OrderManagement.Server.Models.Window", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Window", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "A51",
                            OrderId = 1,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 2,
                            Name = "C Zone 5",
                            OrderId = 1,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "GLB",
                            OrderId = 2,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "OHF",
                            OrderId = 2,
                            Quantity = 10
                        });
                });

            modelBuilder.Entity("OrderManagement.Server.Models.Subelement", b =>
                {
                    b.HasOne("OrderManagement.Server.Models.Window", "Window")
                        .WithMany("Subelements")
                        .HasForeignKey("WindowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Window");
                });

            modelBuilder.Entity("OrderManagement.Server.Models.Window", b =>
                {
                    b.HasOne("OrderManagement.Server.Models.Order", "Order")
                        .WithMany("Windows")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OrderManagement.Server.Models.Order", b =>
                {
                    b.Navigation("Windows");
                });

            modelBuilder.Entity("OrderManagement.Server.Models.Window", b =>
                {
                    b.Navigation("Subelements");
                });
#pragma warning restore 612, 618
        }
    }
}
